### ISSUE TITLE
SPI Module: sclk_enable active out of the shift state

### ISSUE THREAD

**Issue by ana-pgodoy** [TeresaReLo/TOP_FIFO_Modules#2]
According to this line of the specification sclk_enable should only be active during the SHIFT state, however it is active during the COMPLETE state. The signal activates correctly when the SHIFT state start but doesn't turn off when the state change again.

![image](https://github.com/user-attachments/assets/046dc200-71eb-44d5-b02a-fc9af6d3dde7)

![image](https://github.com/user-attachments/assets/54d82540-717a-4843-8665-73500fbc8793)

**Comment by TeresaReLo** [comment]
Hi Ana,

I already solved that problem in the RTL design now the sclk_enable signal is active only during the SHIFT state.
In the following screenshot you can see that when we enter SHIFT state in the same clock cycle the sclk_enable is high and once we enter the COMPLETE state is immediately off.

![image](https://github.com/user-attachments/assets/450fda3e-4cb4-4136-a7c1-7a6a0dbfd02d)

**Comment by ana-pgodoy** [comment]
Hi Teresa,
I saw the changes in the specification and I also adapted the property to these. With the solution in the RTL and the specification changes the property is already passing correctly.  
![image](https://github.com/user-attachments/assets/f593a812-8608-4052-b21a-52f85e8cdf58)
