### ISSUE TITLE
SPI Module: empty signal stops the serialization

### ISSUE THREAD

**Issue by ana-pgodoy** [TeresaReLo/TOP_FIFO_Modules#3]
Hi Teresa.
I found a problem with the empty signal hierarchy and the state machine. According with the states diagram, there are no conditions that change from the LOAD or SHIFT state to IDLE (with the exception of rst which should return the machine to the initial state).  
However, several properties are failing because the empty flag interrupts serialization even though the data has already been read from memory and stored in the shift_reg. In some cases even when the serialization finishes correctly, the done signal isn't sent because the empty signal is received.

![image](https://github.com/user-attachments/assets/40257d63-8c6e-4460-8f8c-f1e641a820f5)

Some of these cases can be seen in the following screenshots:
![image](https://github.com/user-attachments/assets/340b3328-f5ad-48a4-99b2-34e00982b5be)
![image](https://github.com/user-attachments/assets/7ef94b36-4238-40ad-aca1-f607e510c9c4)
![image](https://github.com/user-attachments/assets/41efe32a-21ba-4b96-ba49-702a53b7d324)
![image](https://github.com/user-attachments/assets/9c58b008-8d54-4dfc-9ba3-cdee0c3bd4c9)
![image](https://github.com/user-attachments/assets/4e421111-1897-4547-bf54-e5d331b1a103)
![image](https://github.com/user-attachments/assets/cf401a2e-4e06-4a1f-8d10-d1bc01e5bf63)
![image](https://github.com/user-attachments/assets/f9d615fc-a51f-4545-af3c-26065e2bd6d2)
![image](https://github.com/user-attachments/assets/35d9cabb-138c-440e-bb9a-f62e7238fdb8)
![image](https://github.com/user-attachments/assets/8b964ce4-2878-47d9-896a-aaa067b29e2e)

**Comment by TeresaReLo** [comment]
Hi Ana, 

I already solved that problem in the RTL design there was a problem with the hierarchy of the empty signal acting as a rst signal.
In the following screenshot you can see that even if the empty signal is active during different states, this is no longer interrupting the serialization process and follows the state machine flow until is completed with the last state of done.

![screenshot](https://github.com/user-attachments/assets/c6319700-dd11-4611-a858-d1bf281978f3)

And also, with the modification I make sure that when the empty signal is active and the serialization finish:
- We are stay for the next state in the value of IDLE until a not empty or full signal activated. 

![screenshot](https://github.com/user-attachments/assets/dd514fef-b6eb-4177-a713-df1ec763bf22)

**Comment by ana-pgodoy** [comment]
Hi, I tested the properties again and everything is working fine. I attach the screenshot of the assertions passing in the formal tool as evidence.
![image](https://github.com/user-attachments/assets/668872c6-ab48-4b13-82cb-c8a0e2d52036)
