### ISSUE TITLE
clrh_addr_fsm output FSM signal is not activating when IDLE state.

### ISSUE THREAD

**Issue by TeresaReLo** [TeresaReLo/TOP_FIFO_Modules#4]
Hi Ana!
I found a problem with the clrh_addr_fsm signal for the FSM module. According with you table of states in the documentation, when we enter either to IDLE or CONFI states, the clrh_addr_fsm signal should be activated. 

![image](https://github.com/user-attachments/assets/e7c0d218-ea62-4ffc-832d-2752f611a0d9)

However, we can see in the JasperGold waveform that: 
- The state variable is in the IDLE value.
- And after a rst happen in the same clock cycle the clrh_addr_fsm signal is low contrary to the value of high we expected.

![image](https://github.com/user-attachments/assets/03ccef41-db1e-427f-83ae-e4eb1fc01f38)

**Comment by ana-pgodoy** [comment]
Hi Teresa,
I fixed it, as you can see in the screenshot, the enable clrh_addr_fsm is already activated in the IDLE state correctly.

![image](https://github.com/user-attachments/assets/859307d2-bb53-4132-9aef-a2e5748e345f)

**Comment by TeresaReLo** [comment]
Hi, I already proved the fix that you provided, and it works as can see in the JasperGold tool.

![1bug](https://github.com/user-attachments/assets/9bc00091-40cd-43bd-a80f-f316aaa02d19)

Thanks, 
Teresa R.
